version: "3"

services:
  chatgpt-discord-bot:
    image: petrvlcek/chatgpt-discord-bot:local
    container_name: chatgpt-discord-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f -k -s http://localhost:8000/health | jq -e '.is_healthy == true' > /dev/null" ]
      interval: 30s
      timeout: 5s
      retries: 10
